title: Louis Minion
author: Louis Minion
email: louisalvar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website contains info about me and some of my projects.
theme: minima
# social links
twitter_username: louis_minion # DO NOT include the @ character, or else the build will fail!
github_username:  louisminion # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
Â© 2021 GitHub, Inc.
